# R Markdown


## ioslides: Footnotes

Add this after yaml header

```
<style>
div.footnotes {
  position: absolute;
  bottom: 0;
  margin-bottom: 10px;
  width: 80%;
  font-size: 0.6em;
}
</style>
```


```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

<script>
  $(document).ready(function() {
    $('slide:not(.backdrop):not(.title-slide)').append('<div class=\"footnotes\">');

    $('footnote').each(function(index) {
      var text  = $(this).html();
      var fnNum = (index+1).toString().sup();
      $(this).html(text + fnNum);

      var footnote   = fnNum + ': ' + $(this).attr('content') + '<br/>';
      var oldContent = $(this).parents('slide').children('div.footnotes').html();
      var newContent = oldContent + footnote;
      $(this).parents('slide').children('div.footnotes').html(newContent);
    });
  });
</script>
```


Example footnote:

```
<footnote content = "Dalgaard 2008, Introductory Statistics with R, Springer; O’Neill et al. 1983,  Am. Rev. Respir. Dis., 128:1051–1054."></footnote>
```


##  ioslides: Speaker's notes

Put notes in an html block:

```
<div class="notes">
This is my *note*.

- It can contain markdown
- like this list
</div>
```


Add ?presentme=true to the link for the slides file

Open the file with the augmented link (Chrome works, Safari disables pop-ups).

Press "p" in the top window. Run the slides from the top window, with the other window as the display window.




## How to make multi-line tables



*Some notes on smoothing functions*

These notes come from Faraway, *Extending the Linear Model with R*, p. 302 and Wood, *GAMs*, 1st ed., pp. 124, 128, 148-149, 152-154. 

Using smoothing functions involves a trade-off between model fit and smoothness. If the model is, $y_i = f(x_i) + \epsilon_i$, one simple criterion that could be used is:

$$
\frac{1}{n} \sum (Y_i - f(x_i))^2 + \lambda \int [f''(x)^2] dx \; ,
$$

where $\lambda > 0$ is the smoothing parameter and $\int [f''(x)^2] dx$ is a roughness penalty. This model joins the dots and will be too rough, though, but it illustrates the basic idea behind smoothing. It is the smoothing spline in the table below.

--------------------------------------------------------------------------------------
Type                      Knots                        Notes
------------------------  ---------------------------  --------------------------------
Natural cubic spline\     One knot at each data point  Smoothest possible interpolator;
Smoothing spline                                       wasteful

Cubic regression spline\  Choose where to put knots    Use a basis for smaller data
Penalised regression                                   set than the one to be analysed  spline                                                 (i.e. number of knots much                                                              smaller than sample size);
                                                       still must choose knot locations

P-splines                 Usually evenly spaced        Use a B-spline basis; awkward if
                                                       uneven knot spacing needed

Thin plate splines        Positions determined from    An *ideal* smoother; 
                          mathematical form of         construction of thin plate spline                           model                        determines balance between fit                                                          and smoothness and best                                                                 *function* to achieve                                                              required smoothing
-----------------------------------

Disadvantages of the above types of basis functions:

  -  need to choose knot locations - this introduces extra subjectivity into modelling process
  -  can only be used with one predictor variable
  -  not clear which basis is better or worse than any other basis
  
  

