<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5 Linear Models | Kitab at-Tabakh</title>
  <meta name="description" content="This is a collection of miscellaneous statistics-related recipes and notes." />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="5 Linear Models | Kitab at-Tabakh" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a collection of miscellaneous statistics-related recipes and notes." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5 Linear Models | Kitab at-Tabakh" />
  
  <meta name="twitter:description" content="This is a collection of miscellaneous statistics-related recipes and notes." />
  

<meta name="author" content="Peter Geelan-Small" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="tidyverse.html"/>
<link rel="next" href="linear-mixed-models.html"/>
<script src="libs/header-attrs-2.3/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Intro</a></li>
<li class="chapter" data-level="1" data-path="mawaqif.html"><a href="mawaqif.html"><i class="fa fa-check"></i><b>1</b> Mawaqif</a>
<ul>
<li class="chapter" data-level="1.1" data-path="mawaqif.html"><a href="mawaqif.html#confounders"><i class="fa fa-check"></i><b>1.1</b> Confounders</a></li>
<li class="chapter" data-level="1.2" data-path="mawaqif.html"><a href="mawaqif.html#exponential-models"><i class="fa fa-check"></i><b>1.2</b> Exponential models</a></li>
<li class="chapter" data-level="1.3" data-path="mawaqif.html"><a href="mawaqif.html#power-function"><i class="fa fa-check"></i><b>1.3</b> Power function</a></li>
<li class="chapter" data-level="1.4" data-path="mawaqif.html"><a href="mawaqif.html#variable-selection"><i class="fa fa-check"></i><b>1.4</b> Variable selection</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="mawaqif.html"><a href="mawaqif.html#davison-2003-statistical-models"><i class="fa fa-check"></i><b>1.4.1</b> Davison 2003, Statistical Models</a></li>
<li class="chapter" data-level="1.4.2" data-path="mawaqif.html"><a href="mawaqif.html#faraway-2014-linear-models-with-r"><i class="fa fa-check"></i><b>1.4.2</b> Faraway 2014, Linear Models with R</a></li>
<li class="chapter" data-level="1.4.3" data-path="mawaqif.html"><a href="mawaqif.html#faraway-2016-extending-the-linear-model-with-r-2nd-ed."><i class="fa fa-check"></i><b>1.4.3</b> Faraway 2016, Extending the Linear Model with R, 2nd ed.</a></li>
<li class="chapter" data-level="1.4.4" data-path="mawaqif.html"><a href="mawaqif.html#weisberg-2014-applied-linear-regression-4th-ed."><i class="fa fa-check"></i><b>1.4.4</b> Weisberg 2014, Applied Linear Regression, 4th ed.</a></li>
<li class="chapter" data-level="1.4.5" data-path="mawaqif.html"><a href="mawaqif.html#harrell-2015-regression-modeling-strategies-2nd-ed."><i class="fa fa-check"></i><b>1.4.5</b> Harrell 2015, Regression Modeling Strategies, 2nd ed.</a></li>
<li class="chapter" data-level="1.4.6" data-path="mawaqif.html"><a href="mawaqif.html#david-wartons-draft-book-chapter-5"><i class="fa fa-check"></i><b>1.4.6</b> David Warton’s draft book, chapter 5</a></li>
<li class="chapter" data-level="1.4.7" data-path="mawaqif.html"><a href="mawaqif.html#james-et-al.-introduction-to-statistical-learning-2017-corrected-printing"><i class="fa fa-check"></i><b>1.4.7</b> James et al. Introduction to Statistical Learning, 2017 (corrected printing)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="ggplot.html"><a href="ggplot.html"><i class="fa fa-check"></i><b>2</b> ggplot</a>
<ul>
<li class="chapter" data-level="2.1" data-path="ggplot.html"><a href="ggplot.html#vignettes"><i class="fa fa-check"></i><b>2.1</b> Vignettes</a></li>
<li class="chapter" data-level="2.2" data-path="ggplot.html"><a href="ggplot.html#confidence-bands"><i class="fa fa-check"></i><b>2.2</b> Confidence bands</a></li>
<li class="chapter" data-level="2.3" data-path="ggplot.html"><a href="ggplot.html#histogram"><i class="fa fa-check"></i><b>2.3</b> Histogram</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="ggplot.html"><a href="ggplot.html#histogram-where-data-is-in-one-vector-of-values"><i class="fa fa-check"></i><b>2.3.1</b> Histogram where data is in one vector of values</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="ggplot.html"><a href="ggplot.html#density-plot"><i class="fa fa-check"></i><b>2.4</b> Density plot</a></li>
<li class="chapter" data-level="2.5" data-path="ggplot.html"><a href="ggplot.html#plot-structure"><i class="fa fa-check"></i><b>2.5</b> Plot structure</a></li>
<li class="chapter" data-level="2.6" data-path="ggplot.html"><a href="ggplot.html#label-legend"><i class="fa fa-check"></i><b>2.6</b> Label legend</a></li>
<li class="chapter" data-level="2.7" data-path="ggplot.html"><a href="ggplot.html#plot-title"><i class="fa fa-check"></i><b>2.7</b> Plot title</a></li>
<li class="chapter" data-level="2.8" data-path="ggplot.html"><a href="ggplot.html#three-category-colours"><i class="fa fa-check"></i><b>2.8</b> Three-category colours</a></li>
<li class="chapter" data-level="2.9" data-path="ggplot.html"><a href="ggplot.html#set-breaks-for-scale"><i class="fa fa-check"></i><b>2.9</b> Set breaks for scale</a></li>
<li class="chapter" data-level="2.10" data-path="ggplot.html"><a href="ggplot.html#display-table-to-2-d.p."><i class="fa fa-check"></i><b>2.10</b> Display table to 2 d.p.</a></li>
<li class="chapter" data-level="2.11" data-path="ggplot.html"><a href="ggplot.html#redefine-factor-levels-for-an-individual-plot"><i class="fa fa-check"></i><b>2.11</b> Redefine factor levels for an individual plot</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="r-markdown.html"><a href="r-markdown.html"><i class="fa fa-check"></i><b>3</b> R Markdown</a>
<ul>
<li class="chapter" data-level="3.1" data-path="r-markdown.html"><a href="r-markdown.html#ioslides-footnotes"><i class="fa fa-check"></i><b>3.1</b> ioslides: Footnotes</a></li>
<li class="chapter" data-level="3.2" data-path="r-markdown.html"><a href="r-markdown.html#ioslides-speakers-notes"><i class="fa fa-check"></i><b>3.2</b> ioslides: Speaker’s notes</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="tidyverse.html"><a href="tidyverse.html"><i class="fa fa-check"></i><b>4</b> Tidyverse</a>
<ul>
<li class="chapter" data-level="4.1" data-path="tidyverse.html"><a href="tidyverse.html#stacking-and-unstacking-data"><i class="fa fa-check"></i><b>4.1</b> Stacking and unstacking data</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="linear-models.html"><a href="linear-models.html"><i class="fa fa-check"></i><b>5</b> Linear Models</a>
<ul>
<li class="chapter" data-level="5.1" data-path="linear-models.html"><a href="linear-models.html#anova-orthogonal-factors"><i class="fa fa-check"></i><b>5.1</b> ANOVA: Orthogonal factors</a></li>
<li class="chapter" data-level="5.2" data-path="linear-models.html"><a href="linear-models.html#multiple-linear-regression---conditional-and-marginal-effects"><i class="fa fa-check"></i><b>5.2</b> Multiple linear regression - conditional and marginal effects</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="linear-models.html"><a href="linear-models.html#marginal-and-conditional-interpretations"><i class="fa fa-check"></i><b>5.2.1</b> Marginal and Conditional interpretations</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="linear-models.html"><a href="linear-models.html#linear-model-with-subsampling"><i class="fa fa-check"></i><b>5.3</b> Linear model with subsampling</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="linear-models.html"><a href="linear-models.html#load-necessary-r-packages"><i class="fa fa-check"></i><b>5.3.1</b> Load necessary R packages</a></li>
<li class="chapter" data-level="" data-path="linear-models.html"><a href="linear-models.html#example"><i class="fa fa-check"></i>Example</a></li>
<li class="chapter" data-level="5.3.2" data-path="linear-models.html"><a href="linear-models.html#data"><i class="fa fa-check"></i><b>5.3.2</b> Data</a></li>
<li class="chapter" data-level="5.3.3" data-path="linear-models.html"><a href="linear-models.html#summary-statistics-and-plots"><i class="fa fa-check"></i><b>5.3.3</b> Summary statistics and plots</a></li>
<li class="chapter" data-level="5.3.4" data-path="linear-models.html"><a href="linear-models.html#wrong-analysis-fixed-effects-linear-model"><i class="fa fa-check"></i><b>5.3.4</b> Wrong analysis: fixed effects linear model</a></li>
<li class="chapter" data-level="5.3.5" data-path="linear-models.html"><a href="linear-models.html#right-analysis-mixed-effects-linear-model"><i class="fa fa-check"></i><b>5.3.5</b> Right analysis: mixed effects linear model</a></li>
<li class="chapter" data-level="5.3.6" data-path="linear-models.html"><a href="linear-models.html#an-aside---checking-model-assumptions"><i class="fa fa-check"></i><b>5.3.6</b> An aside - checking model assumptions</a></li>
<li class="chapter" data-level="" data-path="linear-models.html"><a href="linear-models.html#equal-variance-assumption"><i class="fa fa-check"></i>Equal variance assumption</a></li>
<li class="chapter" data-level="" data-path="linear-models.html"><a href="linear-models.html#normal-distribution-assumption"><i class="fa fa-check"></i>Normal distribution assumption</a></li>
<li class="chapter" data-level="5.3.7" data-path="linear-models.html"><a href="linear-models.html#fitted-values-and-confidence-intervals"><i class="fa fa-check"></i><b>5.3.7</b> Fitted values and confidence intervals</a></li>
<li class="chapter" data-level="5.3.8" data-path="linear-models.html"><a href="linear-models.html#another-aside---code-the-nested-structure---not-recommended"><i class="fa fa-check"></i><b>5.3.8</b> Another aside - code the nested structure - not recommended</a></li>
<li class="chapter" data-level="5.3.9" data-path="linear-models.html"><a href="linear-models.html#summary"><i class="fa fa-check"></i><b>5.3.9</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="linear-models.html"><a href="linear-models.html#marginal-means---emmeans-example"><i class="fa fa-check"></i><b>5.4</b> Marginal means - emmeans example</a></li>
<li class="chapter" data-level="5.5" data-path="linear-models.html"><a href="linear-models.html#multiple-regression-example"><i class="fa fa-check"></i><b>5.5</b> Multiple regression example</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="linear-models.html"><a href="linear-models.html#regression-model"><i class="fa fa-check"></i><b>5.5.1</b> Regression model</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html"><i class="fa fa-check"></i><b>6</b> Linear mixed models</a>
<ul>
<li class="chapter" data-level="6.1" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#finding-variance-components-from-lme-models"><i class="fa fa-check"></i><b>6.1</b> Finding variance components from lme models</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Kitab at-Tabakh</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="linear-models" class="section level1" number="5">
<h1><span class="header-section-number">5</span> Linear Models</h1>
<div id="anova-orthogonal-factors" class="section level2" number="5.1">
<h2><span class="header-section-number">5.1</span> ANOVA: Orthogonal factors</h2>
<p><em>Example from Meier, ANOVA (web document)</em></p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="linear-models.html#cb47-1" aria-hidden="true"></a><span class="co">## Create data (skip if not interested) ####</span></span>
<span id="cb47-2"><a href="linear-models.html#cb47-2" aria-hidden="true"></a>acids &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">1.697</span>, <span class="fl">1.601</span>, <span class="fl">1.830</span>,</span>
<span id="cb47-3"><a href="linear-models.html#cb47-3" aria-hidden="true"></a>           <span class="fl">2.032</span>, <span class="fl">2.017</span>, <span class="fl">2.409</span>,</span>
<span id="cb47-4"><a href="linear-models.html#cb47-4" aria-hidden="true"></a>           <span class="fl">2.211</span>, <span class="fl">1.673</span>, <span class="fl">1.973</span>, </span>
<span id="cb47-5"><a href="linear-models.html#cb47-5" aria-hidden="true"></a>           <span class="fl">2.091</span>, <span class="fl">2.255</span>, <span class="fl">2.987</span>)</span>
<span id="cb47-6"><a href="linear-models.html#cb47-6" aria-hidden="true"></a>R50 &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;no&quot;</span>, <span class="st">&quot;yes&quot;</span>, <span class="st">&quot;no&quot;</span>, <span class="st">&quot;yes&quot;</span>), <span class="dt">each =</span> <span class="dv">3</span>)</span>
<span id="cb47-7"><a href="linear-models.html#cb47-7" aria-hidden="true"></a>R21 &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;no&quot;</span>, <span class="st">&quot;no&quot;</span>, <span class="st">&quot;yes&quot;</span>, <span class="st">&quot;yes&quot;</span>), <span class="dt">each =</span> <span class="dv">3</span>)</span>
<span id="cb47-8"><a href="linear-models.html#cb47-8" aria-hidden="true"></a>cheddar &lt;-<span class="st"> </span><span class="kw">data.frame</span>(R50, R21, acids)</span></code></pre></div>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="linear-models.html#cb48-1" aria-hidden="true"></a><span class="kw">str</span>(cheddar)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:	12 obs. of  3 variables:
##  $ R50  : chr  &quot;no&quot; &quot;no&quot; &quot;no&quot; &quot;yes&quot; ...
##  $ R21  : chr  &quot;no&quot; &quot;no&quot; &quot;no&quot; &quot;no&quot; ...
##  $ acids: num  1.7 1.6 1.83 2.03 2.02 ...</code></pre>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="linear-models.html#cb50-1" aria-hidden="true"></a>cheddar</span></code></pre></div>
<pre><code>##    R50 R21 acids
## 1   no  no 1.697
## 2   no  no 1.601
## 3   no  no 1.830
## 4  yes  no 2.032
## 5  yes  no 2.017
## 6  yes  no 2.409
## 7   no yes 2.211
## 8   no yes 1.673
## 9   no yes 1.973
## 10 yes yes 2.091
## 11 yes yes 2.255
## 12 yes yes 2.987</code></pre>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="linear-models.html#cb52-1" aria-hidden="true"></a><span class="kw">table</span>(cheddar<span class="op">$</span>R21, cheddar<span class="op">$</span>R50)</span></code></pre></div>
<pre><code>##      
##       no yes
##   no   3   3
##   yes  3   3</code></pre>
<p>Get model matrix for two-factor model</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="linear-models.html#cb54-1" aria-hidden="true"></a>cheddar.lm1 &lt;-<span class="st"> </span><span class="kw">lm</span>(acids <span class="op">~</span><span class="st"> </span>R21 <span class="op">+</span><span class="st"> </span>R50)</span>
<span id="cb54-2"><a href="linear-models.html#cb54-2" aria-hidden="true"></a><span class="kw">anova</span>(cheddar.lm1)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: acids
##           Df  Sum Sq Mean Sq F value  Pr(&gt;F)  
## R21        1 0.21440 0.21440  2.6526 0.13782  
## R50        1 0.65614 0.65614  8.1178 0.01911 *
## Residuals  9 0.72744 0.08083                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="linear-models.html#cb56-1" aria-hidden="true"></a>cheddar.lm2 &lt;-<span class="st"> </span><span class="kw">lm</span>(acids <span class="op">~</span><span class="st"> </span>R50 <span class="op">+</span><span class="st"> </span>R21)</span>
<span id="cb56-2"><a href="linear-models.html#cb56-2" aria-hidden="true"></a><span class="kw">anova</span>(cheddar.lm2)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: acids
##           Df  Sum Sq Mean Sq F value  Pr(&gt;F)  
## R50        1 0.65614 0.65614  8.1178 0.01911 *
## R21        1 0.21440 0.21440  2.6526 0.13782  
## Residuals  9 0.72744 0.08083                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Sums of squares are the same regardless of the order of R21 and R50 in the model.</p>
<p>Get model matrix.</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="linear-models.html#cb58-1" aria-hidden="true"></a>X &lt;-<span class="st"> </span><span class="kw">model.matrix</span>(cheddar.lm1)</span>
<span id="cb58-2"><a href="linear-models.html#cb58-2" aria-hidden="true"></a></span>
<span id="cb58-3"><a href="linear-models.html#cb58-3" aria-hidden="true"></a>X</span></code></pre></div>
<pre><code>##    (Intercept) R21yes R50yes
## 1            1      0      0
## 2            1      0      0
## 3            1      0      0
## 4            1      0      1
## 5            1      0      1
## 6            1      0      1
## 7            1      1      0
## 8            1      1      0
## 9            1      1      0
## 10           1      1      1
## 11           1      1      1
## 12           1      1      1
## attr(,&quot;assign&quot;)
## [1] 0 1 2
## attr(,&quot;contrasts&quot;)
## attr(,&quot;contrasts&quot;)$R21
## [1] &quot;contr.treatment&quot;
## 
## attr(,&quot;contrasts&quot;)$R50
## [1] &quot;contr.treatment&quot;</code></pre>
<p>Calculate <span class="math inline">\(\textbf{X}&#39;\textbf{X}\)</span></p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="linear-models.html#cb60-1" aria-hidden="true"></a><span class="kw">t</span>(X) <span class="op">%*%</span><span class="st"> </span>X</span></code></pre></div>
<pre><code>##             (Intercept) R21yes R50yes
## (Intercept)          12      6      6
## R21yes                6      6      3
## R50yes                6      3      6</code></pre>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="linear-models.html#cb62-1" aria-hidden="true"></a><span class="kw">solve</span>(<span class="kw">t</span>(X) <span class="op">%*%</span><span class="st"> </span>X)</span></code></pre></div>
<pre><code>##             (Intercept)     R21yes     R50yes
## (Intercept)   0.2500000 -0.1666667 -0.1666667
## R21yes       -0.1666667  0.3333333  0.0000000
## R50yes       -0.1666667  0.0000000  0.3333333</code></pre>
<p><br></p>
</div>
<div id="multiple-linear-regression---conditional-and-marginal-effects" class="section level2" number="5.2">
<h2><span class="header-section-number">5.2</span> Multiple linear regression - conditional and marginal effects</h2>
<p><em>Note: See David’s book, ch. 3.</em></p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="linear-models.html#cb64-1" aria-hidden="true"></a>data_height &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;data/plantHeightSingleSpp.csv&quot;</span>)</span></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   .default = col_double(),
##   Genus_species = col_character(),
##   Family = col_character(),
##   growthform = col_character(),
##   Country = col_character(),
##   Site = col_character(),
##   entered.by = col_character()
## )</code></pre>
<pre><code>## See spec(...) for full column specifications.</code></pre>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="linear-models.html#cb67-1" aria-hidden="true"></a>mod_height1 &lt;-<span class="st"> </span><span class="kw">lm</span>(height <span class="op">~</span><span class="st"> </span>lat, <span class="dt">data =</span> data_height)</span>
<span id="cb67-2"><a href="linear-models.html#cb67-2" aria-hidden="true"></a></span>
<span id="cb67-3"><a href="linear-models.html#cb67-3" aria-hidden="true"></a><span class="kw">summary</span>(mod_height1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = height ~ lat, data = data_height)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -13.558  -6.955  -3.978   3.654  54.333 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 14.42516    1.72433   8.366 1.78e-14 ***
## lat         -0.17631    0.04847  -3.637 0.000362 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 10.95 on 176 degrees of freedom
## Multiple R-squared:  0.06991,	Adjusted R-squared:  0.06463 
## F-statistic: 13.23 on 1 and 176 DF,  p-value: 0.0003617</code></pre>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="linear-models.html#cb69-1" aria-hidden="true"></a>mod_height2 &lt;-<span class="st"> </span><span class="kw">lm</span>(height <span class="op">~</span><span class="st"> </span>rain <span class="op">+</span><span class="st"> </span>lat, <span class="dt">data =</span> data_height)</span>
<span id="cb69-2"><a href="linear-models.html#cb69-2" aria-hidden="true"></a></span>
<span id="cb69-3"><a href="linear-models.html#cb69-3" aria-hidden="true"></a><span class="kw">summary</span>(mod_height2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = height ~ rain + lat, data = data_height)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -14.738  -5.932  -3.418   2.833  52.188 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  4.521724   3.077683   1.469 0.143575    
## rain         0.004058   0.001062   3.823 0.000183 ***
## lat         -0.034109   0.059707  -0.571 0.568547    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 10.55 on 175 degrees of freedom
## Multiple R-squared:  0.1416,	Adjusted R-squared:  0.1318 
## F-statistic: 14.43 on 2 and 175 DF,  p-value: 1.579e-06</code></pre>
<p><br></p>
<p>Reverse order of model terms</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="linear-models.html#cb71-1" aria-hidden="true"></a>mod_height2a &lt;-<span class="st"> </span><span class="kw">lm</span>(height <span class="op">~</span><span class="st"> </span>lat <span class="op">+</span><span class="st"> </span>rain, <span class="dt">data =</span> data_height)</span>
<span id="cb71-2"><a href="linear-models.html#cb71-2" aria-hidden="true"></a></span>
<span id="cb71-3"><a href="linear-models.html#cb71-3" aria-hidden="true"></a><span class="kw">summary</span>(mod_height2a)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = height ~ lat + rain, data = data_height)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -14.738  -5.932  -3.418   2.833  52.188 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  4.521724   3.077683   1.469 0.143575    
## lat         -0.034109   0.059707  -0.571 0.568547    
## rain         0.004058   0.001062   3.823 0.000183 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 10.55 on 175 degrees of freedom
## Multiple R-squared:  0.1416,	Adjusted R-squared:  0.1318 
## F-statistic: 14.43 on 2 and 175 DF,  p-value: 1.579e-06</code></pre>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="linear-models.html#cb73-1" aria-hidden="true"></a><span class="kw">drop1</span>(mod_height2, <span class="dt">test =</span> <span class="st">&quot;F&quot;</span>)</span></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## height ~ rain + lat
##        Df Sum of Sq   RSS    AIC F value    Pr(&gt;F)    
## &lt;none&gt;              19469 841.67                      
## rain    1   1625.55 21094 853.95 14.6117 0.0001834 ***
## lat     1     36.31 19505 840.00  0.3264 0.5685469    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p><br></p>
<div id="marginal-and-conditional-interpretations" class="section level3" number="5.2.1">
<h3><span class="header-section-number">5.2.1</span> Marginal and Conditional interpretations</h3>
<p>The <strong>marginal effect</strong> of a predictor variable in a regression model is the effect of that variable alone on the outcome, estimated without including any other predictor variable in the model.</p>
<p>The model above with <code>lat</code> as the only predictor variable, mod_height1, gives the <strong>marginal effect</strong> of <code>lat</code> as -0.176.</p>
<p>The <strong>conditional effect</strong> of a predictor variable in a regression model is the effect of that variable on the outcome when other predictors are included in the model and all those other predictors are held constant.</p>
<p>The model above with both <code>lat</code> and <code>rain</code> as predictor variables, mod_height2, gives the <strong>conditional effect</strong> of <code>lat</code>, after controlling for the effect of <code>rain</code>, as -0.034.</p>
<p>Note that in R, the “summary” output for “lm” gives the conditional effect of each predictor variable - i.e. the effect conditional on all the other predictor variables, or in other words, after adjusting for or controlling for, all the other predictor variables. This is shown by comparing the three blocks of output immediately above given by summary(mod_height2), summary(mod_height2a) and drop1(mod_height2).</p>
<p><br></p>
</div>
</div>
<div id="linear-model-with-subsampling" class="section level2" number="5.3">
<h2><span class="header-section-number">5.3</span> Linear model with subsampling</h2>
<div id="load-necessary-r-packages" class="section level3" number="5.3.1">
<h3><span class="header-section-number">5.3.1</span> Load necessary R packages</h3>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="linear-models.html#cb75-1" aria-hidden="true"></a><span class="kw">library</span>(gamair)  <span class="co">##  Data</span></span>
<span id="cb75-2"><a href="linear-models.html#cb75-2" aria-hidden="true"></a><span class="kw">library</span>(ggplot2)</span>
<span id="cb75-3"><a href="linear-models.html#cb75-3" aria-hidden="true"></a><span class="kw">library</span>(nlme)</span>
<span id="cb75-4"><a href="linear-models.html#cb75-4" aria-hidden="true"></a><span class="kw">library</span>(emmeans)</span>
<span id="cb75-5"><a href="linear-models.html#cb75-5" aria-hidden="true"></a><span class="kw">library</span>(dplyr)</span></code></pre></div>
</div>
<div id="example" class="section level3 unnumbered">
<h3>Example</h3>
<p><em>Note:</em> This example is from the book, Wood, S. 2017. <em>Generalized Additive Models: An Introduction with R.</em> CRC Press, 2nd ed., pp. 61-65. This book is available as an e-book in UNSW library. (The example is also in the 1st edition of this book on pp. 277-281. Another example of this idea with a different data set, but without the mixed model analysis, is in Steel, R., Torrie, J. and Dickey, D. 1997. <em>Principles and Procedures of Statistics: A Biometrical Approach.</em> McGraw Hill, 3rd ed., pp. 157-165.)</p>
<p>Tree seedlings are grown under two levels of carbon dioxide concentration, with three trees assigned to each treatment. At six months of growth, stomatal area is measured at each of four random locations on each plant.</p>
<p><em>Notes</em></p>
<ul>
<li>“Stomates” are the tiny holes in plant leaves through which carbon dioxide and water vapour are exchanged with the atmosphere during photosynthesis and respiration.</li>
<li>The sample sizes here are artificially small simply to illustrate the ideas.</li>
</ul>
</div>
<div id="data" class="section level3" number="5.3.2">
<h3><span class="header-section-number">5.3.2</span> Data</h3>
<p>The data, “stomata”, is included in the R package, “gamair”.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="linear-models.html#cb76-1" aria-hidden="true"></a><span class="kw">data</span>(stomata)</span></code></pre></div>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="linear-models.html#cb77-1" aria-hidden="true"></a><span class="kw">str</span>(stomata)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:	24 obs. of  3 variables:
##  $ area: num  1.61 1.63 1.54 1.72 1.39 ...
##  $ CO2 : Factor w/ 2 levels &quot;1&quot;,&quot;2&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ tree: Factor w/ 6 levels &quot;1&quot;,&quot;2&quot;,&quot;3&quot;,&quot;4&quot;,..: 1 1 1 1 2 2 2 2 3 3 ...</code></pre>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="linear-models.html#cb79-1" aria-hidden="true"></a><span class="kw">head</span>(stomata)</span></code></pre></div>
<pre><code>##       area CO2 tree
## 1 1.605574   1    1
## 2 1.630071   1    1
## 3 1.539119   1    1
## 4 1.718732   1    1
## 5 1.389616   1    2
## 6 1.585880   1    2</code></pre>
<p>Convert CO2 and tree to factors.</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="linear-models.html#cb81-1" aria-hidden="true"></a>stomata<span class="op">$</span>CO2 &lt;-<span class="st"> </span><span class="kw">factor</span>(stomata<span class="op">$</span>CO2)</span>
<span id="cb81-2"><a href="linear-models.html#cb81-2" aria-hidden="true"></a></span>
<span id="cb81-3"><a href="linear-models.html#cb81-3" aria-hidden="true"></a><span class="co">##  For CO2, &quot;1&quot; is &quot;low&quot; and &quot;2&quot; is &quot;high&quot;.</span></span>
<span id="cb81-4"><a href="linear-models.html#cb81-4" aria-hidden="true"></a><span class="co">##  Add these labels.</span></span>
<span id="cb81-5"><a href="linear-models.html#cb81-5" aria-hidden="true"></a></span>
<span id="cb81-6"><a href="linear-models.html#cb81-6" aria-hidden="true"></a>stomata<span class="op">$</span>CO2 &lt;-<span class="st"> </span><span class="kw">factor</span>(stomata<span class="op">$</span>CO2, <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;low&quot;</span>, <span class="st">&quot;high&quot;</span>))</span>
<span id="cb81-7"><a href="linear-models.html#cb81-7" aria-hidden="true"></a></span>
<span id="cb81-8"><a href="linear-models.html#cb81-8" aria-hidden="true"></a>stomata<span class="op">$</span>tree &lt;-<span class="st"> </span><span class="kw">factor</span>(stomata<span class="op">$</span>tree)</span></code></pre></div>
</div>
<div id="summary-statistics-and-plots" class="section level3" number="5.3.3">
<h3><span class="header-section-number">5.3.3</span> Summary statistics and plots</h3>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="linear-models.html#cb82-1" aria-hidden="true"></a><span class="kw">summary</span>(stomata)</span></code></pre></div>
<pre><code>##       area          CO2     tree 
##  Min.   :0.8753   low :12   1:4  
##  1st Qu.:1.5396   high:12   2:4  
##  Median :2.0166             3:4  
##  Mean   :2.0679             4:4  
##  3rd Qu.:2.7600             5:4  
##  Max.   :3.1149             6:4</code></pre>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="linear-models.html#cb84-1" aria-hidden="true"></a><span class="kw">boxplot</span>(stomata<span class="op">$</span>area <span class="op">~</span><span class="st"> </span>stomata<span class="op">$</span>CO2)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-45-1.png" width="672" /></p>
<p>Plot with a strip plot (strip chart) as sample sizes are small.</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="linear-models.html#cb85-1" aria-hidden="true"></a><span class="kw">stripchart</span>(area <span class="op">~</span><span class="st"> </span>CO2, <span class="dt">data =</span> stomata, <span class="dt">ylab =</span> <span class="st">&quot;CO2 conc.&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-46-1.png" width="672" /></p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="linear-models.html#cb86-1" aria-hidden="true"></a><span class="kw">ggplot</span>(stomata, <span class="kw">aes</span>(<span class="dt">x =</span> CO2, <span class="dt">y =</span> area, <span class="dt">colour =</span> tree)) <span class="op">+</span></span>
<span id="cb86-2"><a href="linear-models.html#cb86-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_jitter</span>(<span class="dt">position =</span> <span class="kw">position_jitter</span>(<span class="fl">0.075</span>))</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-47-1.png" width="672" /></p>
<p>The variance appears fairly constant and the distribution looks fairly symmetric. (This suggests the linear model assumptions will be met, but they’ll be checked later. The purpose of this example is to illustrate the proper way to analyse data from this type of experimental design and not to worry about assumptions, though.)</p>
<p>Note: Where you’ve got data with a quantitative, continuous response variable, the usual function to use for a linear model is “lm”. In the short course, <em>Introductory Statistics for Researchers</em>, we used a function, “aov”, for the one-way ANOVA model we fitted. That function is fairly limited in when you can use it and so “lm” is the function most commonly used. However, there are situations where lm is not appropriate.</p>
<p><br></p>
<p><strong>The following analyses are taken from the book by Simon Wood cited above. Explanations of what’s going on are more detailed in the book. It’s useful to read the material in the book about this example but not to worry about the technical details there.</strong></p>
<p><br></p>
</div>
<div id="wrong-analysis-fixed-effects-linear-model" class="section level3" number="5.3.4">
<h3><span class="header-section-number">5.3.4</span> Wrong analysis: fixed effects linear model</h3>
<p>To account for stomatal area here, we’d expect some contribution from CO2 concentration (there are two levels, low and high) and some contribution from individual trees. The following analysis looks reasonable at face value.</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="linear-models.html#cb87-1" aria-hidden="true"></a>m1 &lt;-<span class="st"> </span><span class="kw">lm</span>(area <span class="op">~</span><span class="st"> </span>CO2 <span class="op">+</span><span class="st"> </span>tree, <span class="dt">data =</span> stomata)</span>
<span id="cb87-2"><a href="linear-models.html#cb87-2" aria-hidden="true"></a></span>
<span id="cb87-3"><a href="linear-models.html#cb87-3" aria-hidden="true"></a><span class="kw">summary</span>(m1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = area ~ CO2 + tree, data = stomata)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.30672 -0.10625 -0.01528  0.08436  0.37674 
## 
## Coefficients: (1 not defined because of singularities)
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  1.62337    0.10932  14.850 1.52e-11 ***
## CO2high      0.70639    0.15460   4.569 0.000238 ***
## tree2       -0.02473    0.15460  -0.160 0.874685    
## tree3       -0.46041    0.15460  -2.978 0.008059 ** 
## tree4        0.45948    0.15460   2.972 0.008166 ** 
## tree5        0.57378    0.15460   3.711 0.001597 ** 
## tree6             NA         NA      NA       NA    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2186 on 18 degrees of freedom
## Multiple R-squared:  0.9215,	Adjusted R-squared:  0.8997 
## F-statistic: 42.24 on 5 and 18 DF,  p-value: 2.511e-09</code></pre>
<p>From above, <span class="math inline">\(P &lt; 0.0001\)</span>. The “NAs” in the output look odd.</p>
<p>The above model is wrong, however, because CO2 and tree are confounded. Trees are nested in CO2 treatments - we cannot, for example, separate the effect of low CO2 from the effect of tree 1 on the predicted value of area for that tree.</p>
<p>Compare the above model with a model including only CO2. The “anova” function below compares the two models - the <span class="math inline">\(P\)</span> value in the output is testing whether the two models are no better than each other.</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="linear-models.html#cb89-1" aria-hidden="true"></a>m0 &lt;-<span class="st"> </span><span class="kw">lm</span>(area <span class="op">~</span><span class="st"> </span>CO2, <span class="dt">data =</span> stomata)</span>
<span id="cb89-2"><a href="linear-models.html#cb89-2" aria-hidden="true"></a></span>
<span id="cb89-3"><a href="linear-models.html#cb89-3" aria-hidden="true"></a><span class="kw">anova</span>(m0, m1)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: area ~ CO2
## Model 2: area ~ CO2 + tree
##   Res.Df    RSS Df Sum of Sq      F   Pr(&gt;F)   
## 1     22 2.1348                                
## 2     18 0.8604  4    1.2744 6.6654 0.001788 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The above output says that the models are not equally good ( <span class="math inline">\(P = 0.002\)</span>, the <span class="math inline">\(P\)</span> value is very small); consequently, the larger model is better - with more explanatory variables, it has more explanatory value. As model m0 contains only CO2 and m1 contains both CO2 and tree, then tree differences are important. However, from those models, we have no way of testing whether CO2 differences are important (as the only difference between the models was whether they included tree or not).</p>
<p>Test for CO2 effects by comparing models with tree but with and without CO2.</p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="linear-models.html#cb91-1" aria-hidden="true"></a>m2 &lt;-<span class="st"> </span><span class="kw">lm</span>(area <span class="op">~</span><span class="st"> </span>tree, <span class="dt">data =</span> stomata)</span>
<span id="cb91-2"><a href="linear-models.html#cb91-2" aria-hidden="true"></a></span>
<span id="cb91-3"><a href="linear-models.html#cb91-3" aria-hidden="true"></a><span class="kw">anova</span>(m2, m1)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: area ~ tree
## Model 2: area ~ CO2 + tree
##   Res.Df    RSS Df  Sum of Sq F Pr(&gt;F)
## 1     18 0.8604                       
## 2     18 0.8604  0 2.2204e-16</code></pre>
<p>The above output shows the two models are the same (the RSS, residual sum of squares, for each is the same) and so we cannot use this analysis to test for CO2 effects. This is caused by the confounding problem.</p>
<p>One way of getting around this problem is to average the response variable values for each tree and use the averaged values as our response variable.</p>
<p><strong>Note you can only do this if there are the same number of data values in each group you average and there are no missing values!</strong></p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="linear-models.html#cb93-1" aria-hidden="true"></a>stomata.avg &lt;-<span class="st"> </span>stomata <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(tree) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb93-2"><a href="linear-models.html#cb93-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">area =</span> <span class="kw">mean</span>(area)) </span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="linear-models.html#cb95-1" aria-hidden="true"></a>CO2_by_tree &lt;-<span class="st"> </span>stomata <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">distinct</span>(tree, CO2)</span>
<span id="cb95-2"><a href="linear-models.html#cb95-2" aria-hidden="true"></a></span>
<span id="cb95-3"><a href="linear-models.html#cb95-3" aria-hidden="true"></a>stomata.avg &lt;-<span class="st"> </span><span class="kw">data.frame</span>(stomata.avg, <span class="dt">CO2 =</span> CO2_by_tree<span class="op">$</span>CO2)</span>
<span id="cb95-4"><a href="linear-models.html#cb95-4" aria-hidden="true"></a>  </span>
<span id="cb95-5"><a href="linear-models.html#cb95-5" aria-hidden="true"></a><span class="kw">str</span>(stomata.avg)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:	6 obs. of  3 variables:
##  $ tree: Factor w/ 6 levels &quot;1&quot;,&quot;2&quot;,&quot;3&quot;,&quot;4&quot;,..: 1 2 3 4 5 6
##  $ area: num  1.62 1.6 1.16 2.79 2.9 ...
##  $ CO2 : Factor w/ 2 levels &quot;low&quot;,&quot;high&quot;: 1 1 1 2 2 2</code></pre>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="linear-models.html#cb97-1" aria-hidden="true"></a>m3 &lt;-<span class="st"> </span><span class="kw">lm</span>(area <span class="op">~</span><span class="st"> </span>CO2, <span class="dt">data =</span> stomata.avg)</span>
<span id="cb97-2"><a href="linear-models.html#cb97-2" aria-hidden="true"></a></span>
<span id="cb97-3"><a href="linear-models.html#cb97-3" aria-hidden="true"></a><span class="kw">summary</span>(m3)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = area ~ CO2, data = stomata.avg)
## 
## Residuals:
##       1       2       3       4       5       6 
##  0.1617  0.1370 -0.2987  0.1151  0.2294 -0.3444 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   1.4617     0.1629   8.970 0.000855 ***
## CO2high       1.2125     0.2304   5.262 0.006247 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2822 on 4 degrees of freedom
## Multiple R-squared:  0.8738,	Adjusted R-squared:  0.8422 
## F-statistic: 27.69 on 1 and 4 DF,  p-value: 0.006247</code></pre>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="linear-models.html#cb99-1" aria-hidden="true"></a><span class="kw">anova</span>(m3)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: area
##           Df  Sum Sq Mean Sq F value   Pr(&gt;F)   
## CO2        1 2.20531 2.20531  27.687 0.006247 **
## Residuals  4 0.31861 0.07965                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The above analysis is valid, although it does involve a two-step process where you average the data for each tree first.</p>
<p>Another way of getting around this problem is to use the “aov” function here. <em>Note the same conditions in bold above apply to using the aov function.</em> We use the original, non-averaged data with aov.</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="linear-models.html#cb101-1" aria-hidden="true"></a>m4 &lt;-<span class="st"> </span><span class="kw">aov</span>(area <span class="op">~</span><span class="st"> </span>CO2 <span class="op">+</span><span class="st"> </span><span class="kw">Error</span>(tree), <span class="dt">data =</span> stomata)</span>
<span id="cb101-2"><a href="linear-models.html#cb101-2" aria-hidden="true"></a></span>
<span id="cb101-3"><a href="linear-models.html#cb101-3" aria-hidden="true"></a><span class="kw">summary</span>(m4)</span></code></pre></div>
<pre><code>## 
## Error: tree
##           Df Sum Sq Mean Sq F value  Pr(&gt;F)   
## CO2        1  8.821   8.821   27.69 0.00625 **
## Residuals  4  1.274   0.319                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Error: Within
##           Df Sum Sq Mean Sq F value Pr(&gt;F)
## Residuals 18 0.8604  0.0478</code></pre>
<p>From the above two analyses, the correct <span class="math inline">\(P\)</span> value for the effect of CO2 is 0.00625.</p>
<p><br></p>
</div>
<div id="right-analysis-mixed-effects-linear-model" class="section level3" number="5.3.5">
<h3><span class="header-section-number">5.3.5</span> Right analysis: mixed effects linear model</h3>
<p>A better (and correct) approach is to use a mixed effects model. <em>This works even if treatment groups do not have the same number of replicates (or if there are missing values).</em></p>
<p>In this approach, tree is included as a grouping variable to identify clusters of data values (i.e. to identify which observed values come from which tree). Observations from the same tree will be correlated to some extent and this needs to be incorporated in the model via a grouping variable. If these groups were not specified in the model, it would appear as if all observations were independent and this would lead to smaller uncertainty in the estimates of treatment effects (because you’d be overstaing the number of independent observations, and hence, the amount of information you really had, or “information value” of your data). The trees in the study are considered as being randomly sampled from the (large) population of trees we are studying. The effects of individual trees are not considered important but they need to be included in the model to identify groups of data values.</p>
<p>So, let’s fit a mixed model. You can use the “nlme” package or the “lme4” package. The nlme package is used here because it gives <span class="math inline">\(P\)</span> values, while the lme4 package does not (another story!).</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="linear-models.html#cb103-1" aria-hidden="true"></a>m5 &lt;-<span class="st"> </span><span class="kw">lme</span>(area <span class="op">~</span><span class="st"> </span>CO2, <span class="dt">random =</span> <span class="op">~</span><span class="st"> </span><span class="dv">1</span> <span class="op">|</span><span class="st"> </span>tree, <span class="dt">data =</span> stomata)</span>
<span id="cb103-2"><a href="linear-models.html#cb103-2" aria-hidden="true"></a></span>
<span id="cb103-3"><a href="linear-models.html#cb103-3" aria-hidden="true"></a><span class="co">#summary(m5)</span></span>
<span id="cb103-4"><a href="linear-models.html#cb103-4" aria-hidden="true"></a></span>
<span id="cb103-5"><a href="linear-models.html#cb103-5" aria-hidden="true"></a><span class="kw">summary</span>(m5)<span class="op">$</span>tTable</span></code></pre></div>
<pre><code>##                Value Std.Error DF  t-value      p-value
## (Intercept) 1.461659 0.1629435 18 8.970341 4.625996e-08
## CO2high     1.212522 0.2304370  4 5.261837 6.246688e-03</code></pre>
<p>From the above output, the <span class="math inline">\(P\)</span> value for the effect of CO2 concentration is 0.00625. This is the same as the <span class="math inline">\(P\)</span> values above using the averaged data and using the aov function.</p>
<p><br></p>
</div>
<div id="an-aside---checking-model-assumptions" class="section level3" number="5.3.6">
<h3><span class="header-section-number">5.3.6</span> An aside - checking model assumptions</h3>
<p>Let’s check the assumptions for the mixed model because we can. This shows how to check the two assumptions of constant variance and Normal distribution for a linear mixed model. We won’t worry here about whether the assumptions are satisfied, as the emphasis is on appropriate methods to use.</p>
</div>
<div id="equal-variance-assumption" class="section level3 unnumbered">
<h3>Equal variance assumption</h3>
<p>Use the plot function with the model name. This produces a residuals vs fitted values plot, which is the standard plot for checking the constant variance assumption.</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="linear-models.html#cb105-1" aria-hidden="true"></a><span class="kw">plot</span>(m5)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-56-1.png" width="672" /></p>
<p>The variances appear to be somewhat unequal.</p>
</div>
<div id="normal-distribution-assumption" class="section level3 unnumbered">
<h3>Normal distribution assumption</h3>
<p>Use a Normal quantile-quantile (Q-Q) plot.</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="linear-models.html#cb106-1" aria-hidden="true"></a><span class="kw">qqnorm</span>(<span class="kw">residuals</span>(m5))</span>
<span id="cb106-2"><a href="linear-models.html#cb106-2" aria-hidden="true"></a><span class="kw">qqline</span>(<span class="kw">residuals</span>(m5))</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-57-1.png" width="672" /></p>
<p>The Normal distribution assumption does not appear to be particularly well met.</p>
<p><br></p>
<p><strong>Back to the main story …</strong></p>
<p>With balanced data, you’ll get the same results from an analysis using aov or lme. However, it’s preferable to use a mixed effects model, as recommended by Simon Wood and described here.</p>
<p><br></p>
</div>
<div id="fitted-values-and-confidence-intervals" class="section level3" number="5.3.7">
<h3><span class="header-section-number">5.3.7</span> Fitted values and confidence intervals</h3>
<p>The R package, “emmeans”, is very useful for getting means and their confidence intervals and plots of these. This package will work with models from lm, aov , lme, ….</p>
<p>Estimates and plots from the fixed effects model using averaged data and the mixed model are below.</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="linear-models.html#cb107-1" aria-hidden="true"></a>m3.emm &lt;-<span class="st"> </span><span class="kw">emmeans</span>(m3, <span class="op">~</span><span class="st"> </span>CO2)</span>
<span id="cb107-2"><a href="linear-models.html#cb107-2" aria-hidden="true"></a></span>
<span id="cb107-3"><a href="linear-models.html#cb107-3" aria-hidden="true"></a><span class="kw">summary</span>(m3.emm)</span></code></pre></div>
<pre><code>##  CO2  emmean    SE df lower.CL upper.CL
##  low    1.46 0.163  4     1.01     1.91
##  high   2.67 0.163  4     2.22     3.13
## 
## Confidence level used: 0.95</code></pre>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="linear-models.html#cb109-1" aria-hidden="true"></a><span class="kw">plot</span>(m3.emm)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-59-1.png" width="672" /></p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="linear-models.html#cb110-1" aria-hidden="true"></a>m5.emm &lt;-<span class="st"> </span><span class="kw">emmeans</span>(m5, <span class="op">~</span>CO2, <span class="dt">mode =</span> <span class="st">&quot;satterthwaite&quot;</span>)</span></code></pre></div>
<pre><code>## Warning in sweep(X, 1, sqrt(weights), &quot;*&quot;): STATS is longer than the
## extent of &#39;dim(x)[MARGIN]&#39;</code></pre>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="linear-models.html#cb112-1" aria-hidden="true"></a><span class="kw">summary</span>(m5.emm)</span></code></pre></div>
<pre><code>##  CO2  emmean    SE   df lower.CL upper.CL
##  low    1.46 0.163 4.02     1.01     1.91
##  high   2.67 0.163 4.02     2.22     3.13
## 
## Degrees-of-freedom method: satterthwaite 
## Confidence level used: 0.95</code></pre>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="linear-models.html#cb114-1" aria-hidden="true"></a><span class="kw">plot</span>(m5.emm)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-61-1.png" width="672" /></p>
<p><br></p>
</div>
<div id="another-aside---code-the-nested-structure---not-recommended" class="section level3" number="5.3.8">
<h3><span class="header-section-number">5.3.8</span> Another aside - code the nested structure - not recommended</h3>
<p>The analysis can be done with lm if the model is coded so that the nesting of trees within CO2 treatments is incorporated. It can only be done this way because, again, the data is balanced and there are no missing values. The full data set is used.</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="linear-models.html#cb115-1" aria-hidden="true"></a>m6 &lt;-<span class="st"> </span><span class="kw">lm</span>(area <span class="op">~</span><span class="st"> </span>CO2 <span class="op">/</span><span class="st"> </span>tree, <span class="dt">data =</span> stomata)</span>
<span id="cb115-2"><a href="linear-models.html#cb115-2" aria-hidden="true"></a></span>
<span id="cb115-3"><a href="linear-models.html#cb115-3" aria-hidden="true"></a><span class="kw">anova</span>(m6)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: area
##           Df Sum Sq Mean Sq  F value    Pr(&gt;F)    
## CO2        1 8.8213  8.8213 184.5452 6.686e-11 ***
## CO2:tree   4 1.2744  0.3186   6.6654  0.001788 ** 
## Residuals 18 0.8604  0.0478                       
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>In the output above, the effect of CO2 needs to be compared against the correct residual term. The <span class="math inline">\(P\)</span> value against CO2 shown in the output is obtained by comparing the variation of CO2 treatments against the variation <em>among observations within trees</em>. This is not the correct comparison. As tree is the experimental unit (leaf is the observational unit), the correct term for the comparison is the term corresponding to the variation <em>between trees within CO2 treatments</em>. In the output, that term is CO2:tree. Consequently, the correct <span class="math inline">\(P\)</span> value for the effect of CO2 is obtained from the <span class="math inline">\(F\)</span> statistic calculated as 8.8213 / 0.3186 (i.e. (Mean Sq for CO2) / (Mean Sq for appropriate residual term)). The calculation for obtaining the <span class="math inline">\(P\)</span> value is below.</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="linear-models.html#cb117-1" aria-hidden="true"></a>f_obs &lt;-<span class="st"> </span><span class="fl">8.8213</span> <span class="op">/</span><span class="st"> </span><span class="fl">0.3186</span></span>
<span id="cb117-2"><a href="linear-models.html#cb117-2" aria-hidden="true"></a></span>
<span id="cb117-3"><a href="linear-models.html#cb117-3" aria-hidden="true"></a>f_obs</span></code></pre></div>
<pre><code>## [1] 27.6877</code></pre>
<p>This is the correct <span class="math inline">\(F\)</span> value, as seen previously.</p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="linear-models.html#cb119-1" aria-hidden="true"></a>p_val &lt;-<span class="st"> </span><span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="kw">pf</span>(f_obs, <span class="dv">1</span>, <span class="dv">4</span>)</span>
<span id="cb119-2"><a href="linear-models.html#cb119-2" aria-hidden="true"></a></span>
<span id="cb119-3"><a href="linear-models.html#cb119-3" aria-hidden="true"></a>p_val</span></code></pre></div>
<pre><code>## [1] 0.00624638</code></pre>
<p>The <span class="math inline">\(P\)</span> value is also clearly the same as seen previously.</p>
<p>It could be awkward to get correct confidence intervals from this model.</p>
<p><br></p>
</div>
<div id="summary" class="section level3" number="5.3.9">
<h3><span class="header-section-number">5.3.9</span> Summary</h3>
<p>When you have subsampling (i.e. multiple measurements made on individual experimental units), use a mixed effects model.</p>
<p>If you have unequal replication across treatments or missing values, definitely use a mixed effects model.</p>
<p><br></p>
</div>
</div>
<div id="marginal-means---emmeans-example" class="section level2" number="5.4">
<h2><span class="header-section-number">5.4</span> Marginal means - emmeans example</h2>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="linear-models.html#cb121-1" aria-hidden="true"></a><span class="kw">library</span>(emmeans)</span>
<span id="cb121-2"><a href="linear-models.html#cb121-2" aria-hidden="true"></a><span class="kw">library</span>(tidyr)</span>
<span id="cb121-3"><a href="linear-models.html#cb121-3" aria-hidden="true"></a><span class="kw">library</span>(dplyr)</span>
<span id="cb121-4"><a href="linear-models.html#cb121-4" aria-hidden="true"></a><span class="kw">library</span>(RcmdrMisc)</span></code></pre></div>
<pre><code>## Loading required package: car</code></pre>
<pre><code>## Loading required package: carData</code></pre>
<pre><code>## 
## Attaching package: &#39;car&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     recode</code></pre>
<pre><code>## The following object is masked from &#39;package:purrr&#39;:
## 
##     some</code></pre>
<pre><code>## The following object is masked from &#39;package:boot&#39;:
## 
##     logit</code></pre>
<pre><code>## Loading required package: sandwich</code></pre>
<p>From the document, <em>Basics of estimated marginal means</em>.</p>
<p><a href="https://cran.r-project.org/web/packages/emmeans/vignettes/basics.html" class="uri">https://cran.r-project.org/web/packages/emmeans/vignettes/basics.html</a></p>
<p>pigs {emmeans} R Documentation</p>
<p>Effects of dietary protein on free plasma leucine concentration in pigs</p>
<p>Description</p>
<p>A two-factor experiment with some observations lost</p>
<p>A data frame with 29 observations and 3 variables:</p>
<ul>
<li>source: Source of protein in the diet (factor with 3 levels: fish meal, soybean meal, dried skim milk)</li>
<li>percent: Protein percentage in the diet (numeric with 4 values: 9, 12, 15, and 18)</li>
<li>conc: Concentration of free plasma leucine, in mcg/ml</li>
</ul>
<p>Source:
Windels HF (1964) PhD thesis, Univ. of Minnesota. (Reported as Problem 10.8 in Oehlert G (2000) A First Course in Design and Analysis of Experiments, licensed under Creative Commons, <a href="http://users.stat.umn.edu/~gary/Book.html" class="uri">http://users.stat.umn.edu/~gary/Book.html</a>.) Observations 7, 22, 23, 31, 33, and 35 have been omitted, creating a more notable imbalance.</p>
<p>[Package emmeans version 1.4.6]</p>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="linear-models.html#cb129-1" aria-hidden="true"></a><span class="kw">data</span>(pigs)</span>
<span id="cb129-2"><a href="linear-models.html#cb129-2" aria-hidden="true"></a></span>
<span id="cb129-3"><a href="linear-models.html#cb129-3" aria-hidden="true"></a>pigs</span></code></pre></div>
<pre><code>##    source percent conc
## 1    fish       9 27.8
## 2    fish       9 23.7
## 3    fish      12 31.5
## 4    fish      12 28.5
## 5    fish      12 32.8
## 6    fish      15 34.0
## 7    fish      15 28.3
## 8    fish      18 30.6
## 9    fish      18 32.7
## 10   fish      18 33.7
## 11    soy       9 39.3
## 12    soy       9 34.8
## 13    soy       9 29.8
## 14    soy      12 39.8
## 15    soy      12 40.0
## 16    soy      12 39.1
## 17    soy      15 38.5
## 18    soy      15 39.2
## 19    soy      15 40.0
## 20    soy      18 42.9
## 21   skim       9 40.6
## 22   skim       9 31.0
## 23   skim       9 34.6
## 24   skim      12 42.9
## 25   skim      12 50.1
## 26   skim      12 37.4
## 27   skim      15 59.5
## 28   skim      15 41.4
## 29   skim      18 59.8</code></pre>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="linear-models.html#cb131-1" aria-hidden="true"></a>pigs<span class="op">$</span>percent &lt;-<span class="st"> </span><span class="kw">factor</span>(pigs<span class="op">$</span>percent)</span></code></pre></div>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="linear-models.html#cb132-1" aria-hidden="true"></a><span class="kw">numSummary</span>(pigs[ , <span class="dv">3</span>], <span class="dt">statistics =</span> <span class="st">&quot;mean&quot;</span>, </span>
<span id="cb132-2"><a href="linear-models.html#cb132-2" aria-hidden="true"></a>           <span class="dt">groups =</span> <span class="kw">interaction</span>(pigs<span class="op">$</span>source, pigs<span class="op">$</span>percent))</span></code></pre></div>
<pre><code>##             mean n
## fish.9  25.75000 2
## soy.9   34.63333 3
## skim.9  35.40000 3
## fish.12 30.93333 3
## soy.12  39.63333 3
## skim.12 43.46667 3
## fish.15 31.15000 2
## soy.15  39.23333 3
## skim.15 50.45000 2
## fish.18 32.33333 3
## soy.18  42.90000 1
## skim.18 59.80000 1</code></pre>
<p><br></p>
<p>Cell means (see also below)</p>
<p>These are arithmetic means of values in each two-way combination</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="linear-models.html#cb134-1" aria-hidden="true"></a><span class="kw">with</span>(pigs, <span class="kw">tapply</span>(conc, <span class="dt">INDEX =</span> <span class="kw">list</span>(source, percent), mean))</span></code></pre></div>
<pre><code>##             9       12       15       18
## fish 25.75000 30.93333 31.15000 32.33333
## soy  34.63333 39.63333 39.23333 42.90000
## skim 35.40000 43.46667 50.45000 59.80000</code></pre>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="linear-models.html#cb136-1" aria-hidden="true"></a><span class="kw">with</span>(pigs, <span class="kw">interaction.plot</span>(percent, source, conc))</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-70-1.png" width="672" /></p>
<p><br></p>
<p>Marginal means</p>
<p>Arithmetic mean of values in each “percent” group</p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="linear-models.html#cb137-1" aria-hidden="true"></a><span class="kw">with</span>(pigs, <span class="kw">tapply</span>(conc, percent, mean))</span></code></pre></div>
<pre><code>##        9       12       15       18 
## 32.70000 38.01111 40.12857 39.94000</code></pre>
<p>Find average for percent = 15</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="linear-models.html#cb139-1" aria-hidden="true"></a>( (<span class="fl">34.0</span> <span class="op">+</span><span class="st"> </span><span class="fl">28.3</span>) <span class="op">+</span><span class="st"> </span>(<span class="fl">38.5</span> <span class="op">+</span><span class="st"> </span><span class="fl">39.2</span> <span class="op">+</span><span class="st"> </span><span class="fl">40.0</span>) <span class="op">+</span><span class="st"> </span>(<span class="fl">59.5</span> <span class="op">+</span><span class="st"> </span><span class="fl">41.4</span>) ) <span class="op">/</span><span class="st"> </span><span class="dv">7</span></span></code></pre></div>
<pre><code>## [1] 40.12857</code></pre>
<p><br></p>
<p>Cell means</p>
<p>Arithmetic means of values in each combination - same as above with two-way tapply call</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="linear-models.html#cb141-1" aria-hidden="true"></a>cell.means &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">with</span>(pigs, </span>
<span id="cb141-2"><a href="linear-models.html#cb141-2" aria-hidden="true"></a>    <span class="kw">tapply</span>(conc, <span class="kw">interaction</span>(source, percent), mean)), </span>
<span id="cb141-3"><a href="linear-models.html#cb141-3" aria-hidden="true"></a>    <span class="dt">nrow =</span> <span class="dv">3</span>)</span>
<span id="cb141-4"><a href="linear-models.html#cb141-4" aria-hidden="true"></a>cell.means</span></code></pre></div>
<pre><code>##          [,1]     [,2]     [,3]     [,4]
## [1,] 25.75000 30.93333 31.15000 32.33333
## [2,] 34.63333 39.63333 39.23333 42.90000
## [3,] 35.40000 43.46667 50.45000 59.80000</code></pre>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="linear-models.html#cb143-1" aria-hidden="true"></a><span class="kw">apply</span>(cell.means, <span class="dv">2</span>, mean)</span></code></pre></div>
<pre><code>## [1] 31.92778 38.01111 40.27778 45.01111</code></pre>
<p>Compare with arithmetic mean of values in each “percent” group</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="linear-models.html#cb145-1" aria-hidden="true"></a><span class="kw">with</span>(pigs, <span class="kw">tapply</span>(conc, percent, mean))</span></code></pre></div>
<pre><code>##        9       12       15       18 
## 32.70000 38.01111 40.12857 39.94000</code></pre>
<p>The two sets are different because the different cells do not all have the same number of observations (some observations were lost).</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="linear-models.html#cb147-1" aria-hidden="true"></a><span class="kw">with</span>(pigs, <span class="kw">table</span>(source, percent))</span></code></pre></div>
<pre><code>##       percent
## source 9 12 15 18
##   fish 2  3  2  3
##   soy  3  3  3  1
##   skim 3  3  2  1</code></pre>
<p>The marginal mean for percent = 12 is the same as the average of the cell means because no observations were lost - i.e. there are equal weights on all the cell means.</p>
<p><br></p>
<p>We can reproduce the <em>marginal means</em> by weighting the cell means with these frequencies. For example, in the last column:</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="linear-models.html#cb149-1" aria-hidden="true"></a><span class="kw">sum</span>(<span class="kw">c</span>(<span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">1</span>) <span class="op">*</span><span class="st"> </span>cell.means[ , <span class="dv">4</span>]) <span class="op">/</span><span class="st"> </span><span class="dv">5</span></span></code></pre></div>
<pre><code>## [1] 39.94</code></pre>
<p><br></p>
</div>
<div id="multiple-regression-example" class="section level2" number="5.5">
<h2><span class="header-section-number">5.5</span> Multiple regression example</h2>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="linear-models.html#cb151-1" aria-hidden="true"></a><span class="kw">library</span>(dplyr)</span>
<span id="cb151-2"><a href="linear-models.html#cb151-2" aria-hidden="true"></a><span class="kw">library</span>(ggplot2)</span>
<span id="cb151-3"><a href="linear-models.html#cb151-3" aria-hidden="true"></a><span class="kw">library</span>(GGally)</span></code></pre></div>
<pre><code>## Registered S3 method overwritten by &#39;GGally&#39;:
##   method from   
##   +.gg   ggplot2</code></pre>
<pre><code>## 
## Attaching package: &#39;GGally&#39;</code></pre>
<pre><code>## The following object is masked _by_ &#39;.GlobalEnv&#39;:
## 
##     pigs</code></pre>
<pre><code>## The following object is masked from &#39;package:emmeans&#39;:
## 
##     pigs</code></pre>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="linear-models.html#cb156-1" aria-hidden="true"></a><span class="kw">library</span>(sjPlot)</span></code></pre></div>
<pre><code>## Registered S3 methods overwritten by &#39;lme4&#39;:
##   method                          from
##   cooks.distance.influence.merMod car 
##   influence.merMod                car 
##   dfbeta.influence.merMod         car 
##   dfbetas.influence.merMod        car</code></pre>
<pre><code>## Install package &quot;strengejacke&quot; from GitHub (`devtools::install_github(&quot;strengejacke/strengejacke&quot;)`) to load all sj-packages at once!</code></pre>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="linear-models.html#cb159-1" aria-hidden="true"></a><span class="kw">library</span>(ggpubr)</span>
<span id="cb159-2"><a href="linear-models.html#cb159-2" aria-hidden="true"></a><span class="kw">library</span>(emmeans)</span></code></pre></div>
<p>Example from StatSci.org - OzDASL, Australian Institute of Sport</p>
<p><a href="http://www.statsci.org/data/oz/ais.html" class="uri">http://www.statsci.org/data/oz/ais.html</a></p>
<p>Variable Description</p>
<p>Sport Sport
Sex male or female
Ht Height in cm
Wt Weight in kg
LBM Lean body mass
RCC Red cell count
WCC White cell count
Hc Hematocrit
Hg Hemoglobin
Ferr Plasma ferritin concentration
BMI Body mass index = weight/height^2
SSF Sum of skin folds
%Bfat % body fat</p>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="linear-models.html#cb160-1" aria-hidden="true"></a>athletes &lt;-<span class="st"> </span><span class="kw">read.table</span>(<span class="st">&quot;http://www.statsci.org/data/oz/ais.txt&quot;</span>, <span class="dt">sep =</span> <span class="st">&quot;&quot;</span>, <span class="dt">header =</span> T)</span>
<span id="cb160-2"><a href="linear-models.html#cb160-2" aria-hidden="true"></a></span>
<span id="cb160-3"><a href="linear-models.html#cb160-3" aria-hidden="true"></a><span class="kw">str</span>(athletes)</span>
<span id="cb160-4"><a href="linear-models.html#cb160-4" aria-hidden="true"></a></span>
<span id="cb160-5"><a href="linear-models.html#cb160-5" aria-hidden="true"></a><span class="kw">save</span>(athletes, <span class="dt">file =</span> <span class="st">&quot;athletes_OzDASL.RData&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="linear-models.html#cb161-1" aria-hidden="true"></a><span class="kw">load</span>(<span class="st">&quot;data/athletes_OzDASL.Rdata&quot;</span>)</span>
<span id="cb161-2"><a href="linear-models.html#cb161-2" aria-hidden="true"></a></span>
<span id="cb161-3"><a href="linear-models.html#cb161-3" aria-hidden="true"></a><span class="kw">str</span>(athletes)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:	202 obs. of  13 variables:
##  $ Sex   : chr  &quot;female&quot; &quot;female&quot; &quot;female&quot; &quot;female&quot; ...
##  $ Sport : chr  &quot;BBall&quot; &quot;BBall&quot; &quot;BBall&quot; &quot;BBall&quot; ...
##  $ RCC   : num  3.96 4.41 4.14 4.11 4.45 4.1 4.31 4.42 4.3 4.51 ...
##  $ WCC   : num  7.5 8.3 5 5.3 6.8 4.4 5.3 5.7 8.9 4.4 ...
##  $ Hc    : num  37.5 38.2 36.4 37.3 41.5 37.4 39.6 39.9 41.1 41.6 ...
##  $ Hg    : num  12.3 12.7 11.6 12.6 14 12.5 12.8 13.2 13.5 12.7 ...
##  $ Ferr  : int  60 68 21 69 29 42 73 44 41 44 ...
##  $ BMI   : num  20.6 20.7 21.9 21.9 19 ...
##  $ SSF   : num  109.1 102.8 104.6 126.4 80.3 ...
##  $ X.Bfat: num  19.8 21.3 19.9 23.7 17.6 ...
##  $ LBM   : num  63.3 58.5 55.4 57.2 53.2 ...
##  $ Ht    : num  196 190 178 185 185 ...
##  $ Wt    : num  78.9 74.4 69.1 74.9 64.6 63.7 75.2 62.3 66.5 62.9 ...</code></pre>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="linear-models.html#cb163-1" aria-hidden="true"></a>athletes<span class="op">$</span>Sex &lt;-<span class="st"> </span><span class="kw">factor</span>(athletes<span class="op">$</span>Sex)</span>
<span id="cb163-2"><a href="linear-models.html#cb163-2" aria-hidden="true"></a></span>
<span id="cb163-3"><a href="linear-models.html#cb163-3" aria-hidden="true"></a>athletes<span class="op">$</span>Sport &lt;-<span class="st"> </span><span class="kw">factor</span>(athletes<span class="op">$</span>Sport)</span>
<span id="cb163-4"><a href="linear-models.html#cb163-4" aria-hidden="true"></a></span>
<span id="cb163-5"><a href="linear-models.html#cb163-5" aria-hidden="true"></a><span class="co">#names( athletes )[names(athletes) == &quot;X.Bfat&quot;] &lt;- &quot;Bfat_pc&quot;</span></span>
<span id="cb163-6"><a href="linear-models.html#cb163-6" aria-hidden="true"></a></span>
<span id="cb163-7"><a href="linear-models.html#cb163-7" aria-hidden="true"></a><span class="co">##  or</span></span>
<span id="cb163-8"><a href="linear-models.html#cb163-8" aria-hidden="true"></a></span>
<span id="cb163-9"><a href="linear-models.html#cb163-9" aria-hidden="true"></a>athletes &lt;-<span class="st"> </span>athletes <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">rename</span>( <span class="dt">Bfat_pc =</span> X.Bfat)</span></code></pre></div>
<div id="regression-model" class="section level3" number="5.5.1">
<h3><span class="header-section-number">5.5.1</span> Regression model</h3>
<p>Response: LBM</p>
<p>Predictors:</p>
<ul>
<li>height</li>
<li>weight</li>
<li>gender</li>
<li>Ferr</li>
</ul>
<p>Include log(Ferr) as suggested on OzDASL web page.</p>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="linear-models.html#cb164-1" aria-hidden="true"></a>athletes<span class="op">$</span>log_Ferr &lt;-<span class="st"> </span><span class="kw">log</span>(athletes<span class="op">$</span>Ferr)</span></code></pre></div>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="linear-models.html#cb165-1" aria-hidden="true"></a><span class="kw">ggpairs</span>(athletes, <span class="dt">columns =</span> <span class="kw">c</span>(<span class="dv">7</span>, <span class="dv">14</span>, <span class="dv">12</span>, <span class="dv">13</span>, <span class="dv">11</span>))</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-83-1.png" width="672" /></p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="linear-models.html#cb166-1" aria-hidden="true"></a><span class="kw">ggplot</span>(athletes, <span class="kw">aes</span>(<span class="dt">x =</span> Sex, <span class="dt">y =</span> LBM)) <span class="op">+</span></span>
<span id="cb166-2"><a href="linear-models.html#cb166-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_boxplot</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-84-1.png" width="672" /></p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="linear-models.html#cb167-1" aria-hidden="true"></a>ath.lm1 &lt;-<span class="st"> </span><span class="kw">lm</span>(LBM <span class="op">~</span><span class="st"> </span>Ht <span class="op">+</span><span class="st"> </span>Wt <span class="op">+</span>log_Ferr <span class="op">+</span><span class="st"> </span>Sex, <span class="dt">data =</span> athletes)</span>
<span id="cb167-2"><a href="linear-models.html#cb167-2" aria-hidden="true"></a></span>
<span id="cb167-3"><a href="linear-models.html#cb167-3" aria-hidden="true"></a><span class="kw">summary</span>(ath.lm1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = LBM ~ Ht + Wt + log_Ferr + Sex, data = athletes)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -11.9543  -1.5237   0.2123   1.6439   8.8396 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -1.30242    5.49116  -0.237   0.8128    
## Ht           0.08320    0.03400   2.447   0.0153 *  
## Wt           0.65455    0.02326  28.141   &lt;2e-16 ***
## log_Ferr    -0.61689    0.35494  -1.738   0.0838 .  
## Sexmale      9.23148    0.51135  18.053   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.713 on 197 degrees of freedom
## Multiple R-squared:  0.9578,	Adjusted R-squared:  0.9569 
## F-statistic:  1117 on 4 and 197 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="linear-models.html#cb169-1" aria-hidden="true"></a>ath.lm2 &lt;-<span class="st"> </span><span class="kw">lm</span>(LBM <span class="op">~</span><span class="st"> </span>Ht , <span class="dt">data =</span> athletes)</span>
<span id="cb169-2"><a href="linear-models.html#cb169-2" aria-hidden="true"></a></span>
<span id="cb169-3"><a href="linear-models.html#cb169-3" aria-hidden="true"></a><span class="kw">summary</span>(ath.lm2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = LBM ~ Ht, data = athletes)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -18.566  -4.913  -0.556   4.171  31.853 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -129.0947    10.2259  -12.62   &lt;2e-16 ***
## Ht             1.0770     0.0567   19.00   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7.825 on 200 degrees of freedom
## Multiple R-squared:  0.6434,	Adjusted R-squared:  0.6416 
## F-statistic: 360.8 on 1 and 200 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="linear-models.html#cb171-1" aria-hidden="true"></a><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb171-2"><a href="linear-models.html#cb171-2" aria-hidden="true"></a><span class="kw">plot</span>(ath.lm1)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-87-1.png" width="672" /></p>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="linear-models.html#cb172-1" aria-hidden="true"></a><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code></pre></div>
<p><br></p>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="linear-models.html#cb173-1" aria-hidden="true"></a>plot1 &lt;-<span class="st"> </span><span class="kw">plot_model</span>(ath.lm1, <span class="dt">type =</span> <span class="st">&quot;pred&quot;</span>, <span class="dt">terms =</span> <span class="st">&quot;Ht&quot;</span>) <span class="op">+</span></span>
<span id="cb173-2"><a href="linear-models.html#cb173-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">ggtitle</span>(<span class="st">&quot;Predicted values of mean LBM with 95 % confidence band&quot;</span>) <span class="op">+</span></span>
<span id="cb173-3"><a href="linear-models.html#cb173-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">plot.title =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">8</span>))</span>
<span id="cb173-4"><a href="linear-models.html#cb173-4" aria-hidden="true"></a></span>
<span id="cb173-5"><a href="linear-models.html#cb173-5" aria-hidden="true"></a><span class="kw">print</span>(plot1)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-88-1.png" width="480" /></p>
<p>The plot above shows a confidence band for predicted mean LBM, as seen by comparing the intervals below with the output of the “predict” function further below.</p>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb174-1"><a href="linear-models.html#cb174-1" aria-hidden="true"></a>plot1<span class="op">$</span>data</span></code></pre></div>
<pre><code>## 
## # Predicted values of LBM
## # x = Ht
## 
##   x | Predicted |   SE | group_col |         95% CI
## ---------------------------------------------------
## 140 |     56.88 | 1.31 |         1 | [54.30, 59.45]
## 150 |     57.71 | 0.99 |         1 | [55.78, 59.64]
## 160 |     58.54 | 0.67 |         1 | [57.22, 59.86]
## 170 |     59.37 | 0.40 |         1 | [58.59, 60.16]
## 180 |     60.20 | 0.32 |         1 | [59.58, 60.83]
## 190 |     61.04 | 0.52 |         1 | [60.01, 62.06]
## 200 |     61.87 | 0.82 |         1 | [60.25, 63.48]
## 210 |     62.70 | 1.15 |         1 | [60.45, 64.95]
## 
## Adjusted for:
## *       Wt =  75.01
## * log_Ferr =   4.16
## *      Sex = female</code></pre>
<p><br></p>
<p>Confidence band - band for fitted mean</p>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb176-1"><a href="linear-models.html#cb176-1" aria-hidden="true"></a>X_new &lt;-<span class="st"> </span><span class="kw">expand.grid</span>(<span class="dt">Ht =</span> <span class="dv">14</span><span class="op">:</span><span class="dv">21</span><span class="op">*</span><span class="dv">10</span>, <span class="dt">Wt =</span> <span class="fl">75.01</span>, <span class="dt">log_Ferr =</span> <span class="fl">4.16</span>, </span>
<span id="cb176-2"><a href="linear-models.html#cb176-2" aria-hidden="true"></a>                     <span class="dt">Sex =</span> <span class="st">&quot;female&quot;</span>)</span>
<span id="cb176-3"><a href="linear-models.html#cb176-3" aria-hidden="true"></a></span>
<span id="cb176-4"><a href="linear-models.html#cb176-4" aria-hidden="true"></a></span>
<span id="cb176-5"><a href="linear-models.html#cb176-5" aria-hidden="true"></a>ath.lm1.pred.CI &lt;-<span class="st"> </span><span class="kw">predict</span>(ath.lm1, <span class="dt">newdata =</span> X_new, <span class="dt">se.fit =</span> T, </span>
<span id="cb176-6"><a href="linear-models.html#cb176-6" aria-hidden="true"></a>                             <span class="dt">type =</span> <span class="st">&quot;response&quot;</span>,</span>
<span id="cb176-7"><a href="linear-models.html#cb176-7" aria-hidden="true"></a>                             <span class="dt">interval =</span> <span class="st">&quot;confidence&quot;</span>)</span>
<span id="cb176-8"><a href="linear-models.html#cb176-8" aria-hidden="true"></a></span>
<span id="cb176-9"><a href="linear-models.html#cb176-9" aria-hidden="true"></a><span class="kw">data.frame</span>(<span class="dt">Ht =</span> <span class="dv">14</span><span class="op">:</span><span class="dv">21</span><span class="op">*</span><span class="dv">10</span>, <span class="dt">se =</span> ath.lm1.pred.CI<span class="op">$</span>se.fit, </span>
<span id="cb176-10"><a href="linear-models.html#cb176-10" aria-hidden="true"></a>           ath.lm1.pred.CI<span class="op">$</span>fit)</span></code></pre></div>
<pre><code>##    Ht        se      fit      lwr      upr
## 1 140 1.3130285 56.87714 54.28775 59.46654
## 2 150 0.9858112 57.70914 55.76505 59.65324
## 3 160 0.6714313 58.54115 57.21703 59.86526
## 4 170 0.4012888 59.37315 58.58177 60.16452
## 5 180 0.3200962 60.20515 59.57389 60.83640
## 6 190 0.5245063 61.03715 60.00278 62.07152
## 7 200 0.8239954 61.86915 60.24417 63.49414
## 8 210 1.1463186 62.70115 60.44052 64.96178</code></pre>
<p>Prediction band - band for single prediction</p>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="linear-models.html#cb178-1" aria-hidden="true"></a>ath.lm1.pred.PI &lt;-<span class="st"> </span><span class="kw">predict</span>(ath.lm1, <span class="dt">newdata =</span> X_new, <span class="dt">se.fit =</span> T, </span>
<span id="cb178-2"><a href="linear-models.html#cb178-2" aria-hidden="true"></a>                             <span class="dt">type =</span> <span class="st">&quot;response&quot;</span>,</span>
<span id="cb178-3"><a href="linear-models.html#cb178-3" aria-hidden="true"></a>                             <span class="dt">interval =</span> <span class="st">&quot;prediction&quot;</span>)</span>
<span id="cb178-4"><a href="linear-models.html#cb178-4" aria-hidden="true"></a></span>
<span id="cb178-5"><a href="linear-models.html#cb178-5" aria-hidden="true"></a><span class="kw">data.frame</span>(<span class="dt">Ht =</span> <span class="dv">14</span><span class="op">:</span><span class="dv">21</span><span class="op">*</span><span class="dv">10</span>, <span class="dt">se =</span> ath.lm1.pred.PI<span class="op">$</span>se.fit, </span>
<span id="cb178-6"><a href="linear-models.html#cb178-6" aria-hidden="true"></a>           ath.lm1.pred.PI<span class="op">$</span>fit)</span></code></pre></div>
<pre><code>##    Ht        se      fit      lwr      upr
## 1 140 1.3130285 56.87714 50.93353 62.82075
## 2 150 0.9858112 57.70914 52.01695 63.40134
## 3 160 0.6714313 58.54115 53.02981 64.05248
## 4 170 0.4012888 59.37315 53.96502 64.78127
## 5 180 0.3200962 60.20515 54.81812 65.59217
## 6 190 0.5245063 61.03715 55.58816 66.48614
## 7 200 0.8239954 61.86915 56.27790 67.46040
## 8 210 1.1463186 62.70115 56.89323 68.50908</code></pre>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb180-1"><a href="linear-models.html#cb180-1" aria-hidden="true"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> athletes, <span class="kw">aes</span>(<span class="dt">x =</span> Ht, <span class="dt">y =</span> LBM)) <span class="op">+</span></span>
<span id="cb180-2"><a href="linear-models.html#cb180-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_point</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-92-1.png" width="672" /></p>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb181-1"><a href="linear-models.html#cb181-1" aria-hidden="true"></a>plot2 &lt;-<span class="st"> </span><span class="kw">plot_model</span>(ath.lm1, <span class="dt">type =</span> <span class="st">&quot;pred&quot;</span>, <span class="dt">terms =</span> <span class="st">&quot;Wt&quot;</span>) <span class="op">+</span></span>
<span id="cb181-2"><a href="linear-models.html#cb181-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">ggtitle</span>(<span class="st">&quot;Predicted values of mean LBM with 95 % confidence band&quot;</span>) <span class="op">+</span></span>
<span id="cb181-3"><a href="linear-models.html#cb181-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">plot.title =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">8</span>))</span>
<span id="cb181-4"><a href="linear-models.html#cb181-4" aria-hidden="true"></a></span>
<span id="cb181-5"><a href="linear-models.html#cb181-5" aria-hidden="true"></a><span class="kw">print</span>(plot2)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-93-1.png" width="480" /></p>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb182-1"><a href="linear-models.html#cb182-1" aria-hidden="true"></a>plot3 &lt;-<span class="st"> </span><span class="kw">plot_model</span>(ath.lm1, <span class="dt">type =</span> <span class="st">&quot;pred&quot;</span>, </span>
<span id="cb182-2"><a href="linear-models.html#cb182-2" aria-hidden="true"></a>                    <span class="dt">terms =</span> <span class="st">&quot;log_Ferr&quot;</span>) <span class="op">+</span></span>
<span id="cb182-3"><a href="linear-models.html#cb182-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">ggtitle</span>(<span class="st">&quot;Predicted values of mean LBM with 95 % confidence band&quot;</span>) <span class="op">+</span></span>
<span id="cb182-4"><a href="linear-models.html#cb182-4" aria-hidden="true"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">plot.title =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">8</span>))</span>
<span id="cb182-5"><a href="linear-models.html#cb182-5" aria-hidden="true"></a></span>
<span id="cb182-6"><a href="linear-models.html#cb182-6" aria-hidden="true"></a><span class="kw">print</span>(plot3)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-94-1.png" width="480" /></p>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb183-1"><a href="linear-models.html#cb183-1" aria-hidden="true"></a>plot4 &lt;-<span class="st"> </span><span class="kw">plot_model</span>(ath.lm1, <span class="dt">type =</span> <span class="st">&quot;pred&quot;</span>, <span class="dt">terms =</span> <span class="st">&quot;Sex&quot;</span>) <span class="op">+</span></span>
<span id="cb183-2"><a href="linear-models.html#cb183-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">ggtitle</span>(<span class="st">&quot;Predicted values of mean LBM with 95 % confidence band&quot;</span>) <span class="op">+</span></span>
<span id="cb183-3"><a href="linear-models.html#cb183-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">plot.title =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">8</span>))</span>
<span id="cb183-4"><a href="linear-models.html#cb183-4" aria-hidden="true"></a></span>
<span id="cb183-5"><a href="linear-models.html#cb183-5" aria-hidden="true"></a><span class="kw">print</span>(plot4)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-95-1.png" width="480" /></p>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb184-1"><a href="linear-models.html#cb184-1" aria-hidden="true"></a>plot4<span class="op">$</span>data</span></code></pre></div>
<pre><code>## 
## # Predicted values of LBM
## # x = Sex
## 
## x | Predicted |   SE | group_col |         95% CI
## -------------------------------------------------
## 1 |     60.21 | 0.32 |         1 | [59.58, 60.84]
## 2 |     69.44 | 0.32 |         1 | [68.82, 70.07]
## 
## Adjusted for:
## *       Ht = 180.10
## *       Wt =  75.01
## * log_Ferr =   4.16</code></pre>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb186-1"><a href="linear-models.html#cb186-1" aria-hidden="true"></a>plot_all &lt;-<span class="st"> </span><span class="kw">ggarrange</span>(plot1, plot2, plot3, plot4, <span class="dt">nrow =</span> <span class="dv">2</span>, </span>
<span id="cb186-2"><a href="linear-models.html#cb186-2" aria-hidden="true"></a>                      <span class="dt">ncol =</span> <span class="dv">2</span>)</span>
<span id="cb186-3"><a href="linear-models.html#cb186-3" aria-hidden="true"></a></span>
<span id="cb186-4"><a href="linear-models.html#cb186-4" aria-hidden="true"></a><span class="kw">print</span>(plot_all)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-97-1.png" width="672" /></p>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb187-1"><a href="linear-models.html#cb187-1" aria-hidden="true"></a><span class="kw">pdf</span>(<span class="dt">file =</span> <span class="st">&quot;athletes_reg_plot_panel.pdf&quot;</span>, <span class="dt">width =</span> <span class="dv">7</span>, </span>
<span id="cb187-2"><a href="linear-models.html#cb187-2" aria-hidden="true"></a>    <span class="dt">height =</span> <span class="dv">5</span>)</span>
<span id="cb187-3"><a href="linear-models.html#cb187-3" aria-hidden="true"></a></span>
<span id="cb187-4"><a href="linear-models.html#cb187-4" aria-hidden="true"></a>plot_all</span>
<span id="cb187-5"><a href="linear-models.html#cb187-5" aria-hidden="true"></a></span>
<span id="cb187-6"><a href="linear-models.html#cb187-6" aria-hidden="true"></a><span class="kw">dev.off</span>()</span></code></pre></div>
<pre><code>## quartz_off_screen 
##                 2</code></pre>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="tidyverse.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="linear-mixed-models.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": null
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
